/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI;

import java.io.File;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import model.UserProfile;

/**
 *
 * @author mayan
 */
public class CreateJPanel extends javax.swing.JPanel {

    UserProfile userProfile;
    private String bioPathString;
    private String photoPathString;
    private boolean nameFlag;
    private boolean phoneNoFlag;
    private boolean faxFlag;
    private boolean emailFlag;
    private boolean SSNFlag;
    private boolean IPFlag;
    private boolean accountFlag;
    private boolean bioFlag;
    private boolean photoFlag;
    private boolean flag;

    /**
     * Creates new form NewJPanel
     */
    public CreateJPanel(UserProfile userProfile) {
        initComponents();
        this.userProfile = userProfile;
        setSize(1500,1024);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        CreateProfile = new javax.swing.JLabel();
        userName = new javax.swing.JLabel();
        userAddress = new javax.swing.JLabel();
        phoneNo = new javax.swing.JLabel();
        faxNo = new javax.swing.JLabel();
        useEmail = new javax.swing.JLabel();
        ssn = new javax.swing.JLabel();
        mrn = new javax.swing.JLabel();
        healthPlanNo = new javax.swing.JLabel();
        accountNo = new javax.swing.JLabel();
        licenseNo = new javax.swing.JLabel();
        vehicleNo = new javax.swing.JLabel();
        deviceNo = new javax.swing.JLabel();
        linkedin = new javax.swing.JLabel();
        ipAddress = new javax.swing.JLabel();
        bioLabel = new javax.swing.JLabel();
        addressText = new javax.swing.JTextField();
        nameText = new javax.swing.JTextField();
        phoneNoText = new javax.swing.JTextField();
        ssnText = new javax.swing.JTextField();
        emailText = new javax.swing.JTextField();
        faxText = new javax.swing.JTextField();
        mrnText = new javax.swing.JTextField();
        licenseNoText = new javax.swing.JTextField();
        ipAddressText = new javax.swing.JTextField();
        linkedinText = new javax.swing.JTextField();
        deviceSerialNo = new javax.swing.JTextField();
        accountNoText = new javax.swing.JTextField();
        healthPlanNoText = new javax.swing.JTextField();
        vehicleSerialNoText = new javax.swing.JTextField();
        userPhotoLabel = new javax.swing.JLabel();
        uniqueCodeLabel = new javax.swing.JLabel();
        uniqueCodeText = new javax.swing.JTextField();
        jLabel37 = new javax.swing.JLabel();
        bioButton = new javax.swing.JButton();
        photoButton = new javax.swing.JButton();
        photoPath = new javax.swing.JLabel();
        bioPath = new javax.swing.JLabel();
        saveButton = new javax.swing.JButton();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        errName = new javax.swing.JLabel();
        errPhone = new javax.swing.JLabel();
        errEmail = new javax.swing.JLabel();
        errFax = new javax.swing.JLabel();
        errSSN = new javax.swing.JLabel();
        errIp = new javax.swing.JLabel();
        errAccountNo = new javax.swing.JLabel();

        setBackground(new java.awt.Color(0, 153, 153));

        CreateProfile.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        CreateProfile.setText("Create User Profile");
        CreateProfile.setAutoscrolls(true);

        userName.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        userName.setText("Name:");

        userAddress.setText("Address:");

        phoneNo.setText("Phone Number:");

        faxNo.setText("Fax Number:");

        useEmail.setText("User Email:");

        ssn.setText("Social Security Number:");

        mrn.setText("Medical Record Number:");

        healthPlanNo.setText("Health Plan Benerficiary Number:");

        accountNo.setText("Bank Account Number:");

        licenseNo.setText("License Number:");

        vehicleNo.setText("Vehicle Serial Number:");

        deviceNo.setText("Device Serial Number:");

        linkedin.setText("LinkedIn:");

        ipAddress.setText("IP Address:");

        bioLabel.setText("Biometric Identifiers:");

        nameText.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                nameTextKeyReleased(evt);
            }
        });

        phoneNoText.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                phoneNoTextKeyReleased(evt);
            }
        });

        ssnText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ssnTextActionPerformed(evt);
            }
        });
        ssnText.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                ssnTextKeyReleased(evt);
            }
        });

        emailText.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                emailTextKeyReleased(evt);
            }
        });

        faxText.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                faxTextKeyReleased(evt);
            }
        });

        mrnText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mrnTextActionPerformed(evt);
            }
        });

        ipAddressText.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                ipAddressTextKeyReleased(evt);
            }
        });

        accountNoText.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                accountNoTextKeyReleased(evt);
            }
        });

        userPhotoLabel.setText("User Photo:");

        uniqueCodeLabel.setText("Unique Identifiers Code:");

        jLabel37.setText("Date of Birth:");

        bioButton.setText("Upload Biometric Here");
        bioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bioButtonActionPerformed(evt);
            }
        });

        photoButton.setText("Upload Photo Here");
        photoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                photoButtonActionPerformed(evt);
            }
        });

        saveButton.setText("Save Profile");
        saveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(240, 240, 240)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(userName)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(healthPlanNo)
                                        .addComponent(userAddress, javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(phoneNo, javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(faxNo, javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(useEmail, javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(ssn, javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(mrn, javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(accountNo, javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(licenseNo, javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(vehicleNo, javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(deviceNo, javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(linkedin, javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(ipAddress, javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(bioLabel, javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(uniqueCodeLabel, javax.swing.GroupLayout.Alignment.TRAILING))
                                    .addComponent(jLabel37)
                                    .addComponent(userPhotoLabel))
                                .addGap(69, 69, 69)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(nameText)
                                    .addComponent(addressText)
                                    .addComponent(phoneNoText)
                                    .addComponent(faxText)
                                    .addComponent(emailText)
                                    .addComponent(ssnText)
                                    .addComponent(mrnText)
                                    .addComponent(healthPlanNoText)
                                    .addComponent(accountNoText)
                                    .addComponent(licenseNoText)
                                    .addComponent(vehicleSerialNoText)
                                    .addComponent(deviceSerialNo)
                                    .addComponent(linkedinText)
                                    .addComponent(ipAddressText)
                                    .addComponent(uniqueCodeText)
                                    .addComponent(bioButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(photoButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(saveButton, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(115, 115, 115)))
                        .addGap(23, 23, 23)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(errEmail, javax.swing.GroupLayout.DEFAULT_SIZE, 294, Short.MAX_VALUE)
                            .addComponent(errAccountNo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(errName, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(errPhone, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(errFax, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(errSSN, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(errIp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(bioPath, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(photoPath, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(117, 117, 117)
                        .addComponent(CreateProfile, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(238, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(CreateProfile, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(userName)
                    .addComponent(nameText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(errName, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addressText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(userAddress))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel37))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(phoneNo)
                    .addComponent(phoneNoText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(errPhone, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(faxNo)
                    .addComponent(faxText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(errFax, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(useEmail)
                    .addComponent(emailText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(errEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ssn)
                    .addComponent(ssnText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(errSSN, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(mrn)
                    .addComponent(mrnText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(healthPlanNo)
                    .addComponent(healthPlanNoText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(accountNo)
                                    .addComponent(errAccountNo, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(licenseNo)
                                    .addComponent(licenseNoText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(accountNoText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(vehicleNo))
                    .addComponent(vehicleSerialNoText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(deviceSerialNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(deviceNo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(linkedin)
                    .addComponent(linkedinText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ipAddressText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ipAddress)
                    .addComponent(errIp, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(bioPath, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(bioLabel)
                        .addComponent(bioButton)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(userPhotoLabel)
                            .addComponent(photoButton))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(uniqueCodeLabel)
                            .addComponent(uniqueCodeText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(27, 27, 27)
                        .addComponent(saveButton, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(photoPath, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 355, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void mrnTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mrnTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mrnTextActionPerformed

    private void ssnTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ssnTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ssnTextActionPerformed

    private void saveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveButtonActionPerformed
        // TODO add your handling code here:
        flag = !(addressText.getText().length()<=0 || mrnText.getText().length()<=0 ||
                healthPlanNoText.getText().length()<=0 || licenseNoText.getText().length()<=0 ||
                vehicleSerialNoText.getText().length()<=0 || deviceSerialNo.getText().length()<=0||
                linkedinText.getText().length()<=0 || ipAddressText.getText().length()<=0 ||
                uniqueCodeText.getText().length()<=0);
        
        if(flag && nameFlag && phoneNoFlag && faxFlag && SSNFlag && emailFlag && IPFlag && photoFlag && bioFlag && accountFlag){
        
        userProfile.setUserName(nameText.getText());
        userProfile.setUserAddress(addressText.getText());
        SimpleDateFormat formatter = new SimpleDateFormat("MM/dd/yyyy");  
        String strDate= formatter.format(jDateChooser1.getDate());
        userProfile.setUserDob(strDate);
        userProfile.setPhoneNo(Long.parseLong(phoneNoText.getText()));
        userProfile.setFax(Long.parseLong(faxText.getText()));
        userProfile.setUserEmail(emailText.getText());
        userProfile.setSsn(ssnText.getText());
        userProfile.setMedicalRecord(mrnText.getText());
        userProfile.setUserHealthPlanNo(healthPlanNoText.getText());
        userProfile.setBankAccountNo(Long.parseLong(accountNoText.getText()));
        userProfile.setLicenseNo(licenseNoText.getText());
        userProfile.setVehicleNo(vehicleSerialNoText.getText());
        userProfile.setDeviceSerialNo(deviceSerialNo.getText());
        userProfile.setLinkedin(linkedinText.getText());
        userProfile.setIpAddress(ipAddressText.getText());
        userProfile.setBiometricIdentifier(bioPathString);
        userProfile.setProfilePhoto(photoPathString);
        userProfile.setUniqueIdentifier(uniqueCodeText.getText());

        JOptionPane.showMessageDialog(this, "User Profile Saved");
        }
        else {
        JOptionPane.showMessageDialog(this, "Please enter valid data");
        }
        
    }//GEN-LAST:event_saveButtonActionPerformed

    private void bioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bioButtonActionPerformed
        // TODO add your handling code here:
        JFileChooser biometric = new JFileChooser();
        biometric.showSaveDialog(null);
        
        File f = biometric.getSelectedFile();
        bioPathString = f.getAbsolutePath();
        //bioPath.setText(bioPathString);
        String regex = "([^\\s]+(\\.(?i)(/jpeg|jpg|gif|png))$)";
        Pattern pattern = Pattern.compile(regex);
        Matcher match = pattern.matcher(bioPathString);
        if(bioPathString.length()<1 || !match.matches()){
            bioPath.setText("Biometric Image could not be uploaded");
            bioFlag = false;
        }
        else {
        //bioPathString.setText(null);
        bioFlag = true;
        bioPath.setText(bioPathString);
        }
    }//GEN-LAST:event_bioButtonActionPerformed

    private void photoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_photoButtonActionPerformed
        // TODO add your handling code here:
        JFileChooser biometric = new JFileChooser();
        biometric.showSaveDialog(null);
        
        File f = biometric.getSelectedFile();
        photoPathString = f.getAbsolutePath();
        String regex = "([^\\s]+(\\.(?i)(/jpeg|jpg|gif|png))$)";
        Pattern pattern= Pattern.compile(regex);
        Matcher match=pattern.matcher(photoPathString);
        if(photoPathString.length()<1 || !match.matches()){
          photoPath.setText("Profile Image uploaded is wrong.");
          photoFlag = false;
        }
        else {
        //photoPath.setText(null);
        photoFlag = true;
        photoPath.setText(photoPathString);
        }
    }//GEN-LAST:event_photoButtonActionPerformed

    private void nameTextKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nameTextKeyReleased
        // TODO add your handling code here:
        String regex = "([a-zA-Z][a-zA-Z ]*)";
        Pattern pattern= Pattern.compile(regex);
        Matcher match=pattern.matcher(nameText.getText());
        if(nameText.getText().length()<1 || !match.matches()){
            errName.setText("User Name invalid");
            nameFlag = false;
        }
        else {
        errName.setText(null);
        nameFlag = true;
        }
    }//GEN-LAST:event_nameTextKeyReleased

    private void phoneNoTextKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_phoneNoTextKeyReleased
        // TODO add your handling code here:
        String regex = "\\d{10}";
        Pattern pattern= Pattern.compile(regex);
        Matcher match=pattern.matcher(phoneNoText.getText());
       
        if(phoneNoText.getText().length()<=0 || phoneNoText.getText().length()>10 || !match.matches()){
        errPhone.setText("Phone number is incorrect");
        phoneNoFlag = false;
        }
        else {
        errPhone.setText(null);
        phoneNoFlag = true;
        }
    }//GEN-LAST:event_phoneNoTextKeyReleased

    private void faxTextKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_faxTextKeyReleased
        // TODO add your handling code here:
        String regex = "\\d{10}";
        Pattern pattern= Pattern.compile(regex);
        Matcher match=pattern.matcher(faxText.getText());
       
        if(faxText.getText().length()<=0 || faxText.getText().length()>10 || !match.matches()){
        errFax.setText("FAX number is invalid");
        faxFlag = false;
        }
        else {
        errFax.setText(null);
        faxFlag = true;
        }
    }//GEN-LAST:event_faxTextKeyReleased

    private void emailTextKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_emailTextKeyReleased
        // TODO add your handling code here:
        String regex = "^[a-zA-Z0-9+_.-]+[@][a-zA-Z0-9.-]+[.][a-zA-Z]+$";
        Pattern pattern= Pattern.compile(regex);
        Matcher match=pattern.matcher(emailText.getText());
        if(emailText.getText().length()<=0 || !match.matches()){
        errEmail.setText("Email ID entered is incorrect, @,. is required");
        emailFlag = false;
        }
        else {
        errEmail.setText(null);
        emailFlag = true;
        }
    }//GEN-LAST:event_emailTextKeyReleased

    private void ssnTextKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ssnTextKeyReleased
        // TODO add your handling code here:
        String regex = "^(?!666|000|9\\d{2})\\d{3}" + "-(?!00)\\d{2}-" + "(?!0{4})\\d{4}$";
        Pattern pattern= Pattern.compile(regex);
        Matcher match=pattern.matcher(ssnText.getText());
        if(ssnText.getText().length()<=0 || !match.matches()){
        errSSN.setText("SSN Number is invalid. Please enter corect SSN with -");
        SSNFlag = false;
        }
        else {
        errSSN.setText(null);
        SSNFlag = true;
        }
    }//GEN-LAST:event_ssnTextKeyReleased

    private void ipAddressTextKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ipAddressTextKeyReleased
        // TODO add your handling code here:
        String zeroTo255 = "(\\d{1,2}|(0|1)\\d{2}|2[0-4]\\d|25[0-5])";
        String regex = zeroTo255 + "\\." + zeroTo255 + "\\." + zeroTo255 + "\\." + zeroTo255;
        Pattern pattern= Pattern.compile(regex);
        Matcher match=pattern.matcher(ipAddressText.getText());
        if(ipAddressText.getText().length()<=0 || !match.matches()){
        errIp.setText("IP Address is incorrect");
        IPFlag = false;
        }
        else {
        errIp.setText(null);
        IPFlag = true;
        }
    }//GEN-LAST:event_ipAddressTextKeyReleased

    private void accountNoTextKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_accountNoTextKeyReleased
        // TODO add your handling code here:
        String regex = "\\d+";
        Pattern pattern= Pattern.compile(regex);
        Matcher match=pattern.matcher(accountNoText.getText());
       
        if(accountNoText.getText().length()<=0 || !match.matches()){
        errAccountNo.setText("Account number is invalid");
        accountFlag = false;
        }
        else {
        errAccountNo.setText(null);
        accountFlag = true;
        }
    }//GEN-LAST:event_accountNoTextKeyReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel CreateProfile;
    private javax.swing.JLabel accountNo;
    private javax.swing.JTextField accountNoText;
    private javax.swing.JTextField addressText;
    private javax.swing.JButton bioButton;
    private javax.swing.JLabel bioLabel;
    private javax.swing.JLabel bioPath;
    private javax.swing.JLabel deviceNo;
    private javax.swing.JTextField deviceSerialNo;
    private javax.swing.JTextField emailText;
    private javax.swing.JLabel errAccountNo;
    private javax.swing.JLabel errEmail;
    private javax.swing.JLabel errFax;
    private javax.swing.JLabel errIp;
    private javax.swing.JLabel errName;
    private javax.swing.JLabel errPhone;
    private javax.swing.JLabel errSSN;
    private javax.swing.JLabel faxNo;
    private javax.swing.JTextField faxText;
    private javax.swing.JLabel healthPlanNo;
    private javax.swing.JTextField healthPlanNoText;
    private javax.swing.JLabel ipAddress;
    private javax.swing.JTextField ipAddressText;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel licenseNo;
    private javax.swing.JTextField licenseNoText;
    private javax.swing.JLabel linkedin;
    private javax.swing.JTextField linkedinText;
    private javax.swing.JLabel mrn;
    private javax.swing.JTextField mrnText;
    private javax.swing.JTextField nameText;
    private javax.swing.JLabel phoneNo;
    private javax.swing.JTextField phoneNoText;
    private javax.swing.JButton photoButton;
    private javax.swing.JLabel photoPath;
    private javax.swing.JButton saveButton;
    private javax.swing.JLabel ssn;
    private javax.swing.JTextField ssnText;
    private javax.swing.JLabel uniqueCodeLabel;
    private javax.swing.JTextField uniqueCodeText;
    private javax.swing.JLabel useEmail;
    private javax.swing.JLabel userAddress;
    private javax.swing.JLabel userName;
    private javax.swing.JLabel userPhotoLabel;
    private javax.swing.JLabel vehicleNo;
    private javax.swing.JTextField vehicleSerialNoText;
    // End of variables declaration//GEN-END:variables
}
