/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI;

import javax.swing.ImageIcon;
import model.UserProfile;

/**
 *
 * @author mayan
 */
public class ViewJPanel extends javax.swing.JPanel {

    private final UserProfile userProfile;
    private ImageIcon icon;

    /**
     * Creates new form NewJPanel1
     */
    public ViewJPanel(UserProfile userProfile) {
        initComponents();
        setSize(1500,1024);
        this.userProfile = userProfile;
        displayProfile();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dobText = new javax.swing.JTextField();
        ssnText = new javax.swing.JTextField();
        emailText = new javax.swing.JTextField();
        userName = new javax.swing.JLabel();
        faxText = new javax.swing.JTextField();
        userAddress = new javax.swing.JLabel();
        mrnText = new javax.swing.JTextField();
        licenseNoText = new javax.swing.JTextField();
        phoneNo = new javax.swing.JLabel();
        ipAddressText = new javax.swing.JTextField();
        faxNo = new javax.swing.JLabel();
        linkedinText = new javax.swing.JTextField();
        useEmail = new javax.swing.JLabel();
        deviceSerialNo = new javax.swing.JTextField();
        ssn = new javax.swing.JLabel();
        mrn = new javax.swing.JLabel();
        healthPlanNo = new javax.swing.JLabel();
        accountNoText = new javax.swing.JTextField();
        healthPlanNoText = new javax.swing.JTextField();
        userPhotoLabel = new javax.swing.JLabel();
        accountNo = new javax.swing.JLabel();
        vehicleSerialNoText = new javax.swing.JTextField();
        uniqueCodeLabel = new javax.swing.JLabel();
        licenseNo = new javax.swing.JLabel();
        vehicleNo = new javax.swing.JLabel();
        uniqueCodeText = new javax.swing.JTextField();
        deviceNo = new javax.swing.JLabel();
        linkedin = new javax.swing.JLabel();
        ipAddress = new javax.swing.JLabel();
        bioLabel = new javax.swing.JLabel();
        addressText = new javax.swing.JTextField();
        nameText = new javax.swing.JTextField();
        userDob = new javax.swing.JLabel();
        phoneNoText = new javax.swing.JTextField();
        Title = new javax.swing.JLabel();
        biometricImage = new javax.swing.JLabel();
        userImage = new javax.swing.JLabel();

        setBackground(new java.awt.Color(0, 153, 153));

        dobText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dobTextActionPerformed(evt);
            }
        });

        ssnText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ssnTextActionPerformed(evt);
            }
        });

        userName.setText("Name:");

        userAddress.setText("Address:");

        mrnText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mrnTextActionPerformed(evt);
            }
        });

        phoneNo.setText("Phone Number:");

        faxNo.setText("Fax Number:");

        useEmail.setText("User Email:");

        ssn.setText("Social Security Number:");

        mrn.setText("Medical Record Number:");

        healthPlanNo.setText("Health Plan Benerficiary Number:");

        userPhotoLabel.setText("User Photo:");

        accountNo.setText("Bank Account Number:");

        uniqueCodeLabel.setText("Unique Identifiers Code:");

        licenseNo.setText("License Number:");

        vehicleNo.setText("Vehicle Serial Number:");

        deviceNo.setText("Device Serial Number:");

        linkedin.setText("LinkedIn:");

        ipAddress.setText("IP Address:");

        bioLabel.setText("Biometric Identifiers:");

        userDob.setText("Date of Birth:");

        Title.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        Title.setText("View User Profile");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(80, 80, 80)
                        .addComponent(userPhotoLabel))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(68, 68, 68)
                        .addComponent(bioLabel))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addComponent(biometricImage, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 130, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(214, 214, 214)
                        .addComponent(Title, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(userName)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(healthPlanNo)
                                .addComponent(userAddress, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(phoneNo, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(faxNo, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(useEmail, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(ssn, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(mrn, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(accountNo, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(licenseNo, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(vehicleNo, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(deviceNo, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(linkedin, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(ipAddress, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(uniqueCodeLabel, javax.swing.GroupLayout.Alignment.TRAILING))
                            .addComponent(userDob))
                        .addGap(69, 69, 69)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(nameText, javax.swing.GroupLayout.DEFAULT_SIZE, 253, Short.MAX_VALUE)
                            .addComponent(addressText)
                            .addComponent(dobText)
                            .addComponent(phoneNoText)
                            .addComponent(faxText)
                            .addComponent(emailText)
                            .addComponent(ssnText)
                            .addComponent(mrnText)
                            .addComponent(healthPlanNoText)
                            .addComponent(vehicleSerialNoText)
                            .addComponent(linkedinText)
                            .addComponent(licenseNoText, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(accountNoText, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(deviceSerialNo, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ipAddressText)
                            .addComponent(uniqueCodeText))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(42, 42, 42)
                    .addComponent(userImage, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(621, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(124, 124, 124)
                .addComponent(userPhotoLabel)
                .addGap(208, 208, 208)
                .addComponent(bioLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(biometricImage, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(uniqueCodeLabel))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addComponent(Title, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(36, 36, 36)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(userName)
                            .addComponent(nameText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(addressText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(userAddress))
                        .addGap(13, 13, 13)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(userDob)
                            .addComponent(dobText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(phoneNo)
                            .addComponent(phoneNoText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(faxNo)
                            .addComponent(faxText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(useEmail)
                            .addComponent(emailText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ssn)
                            .addComponent(ssnText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(mrn)
                            .addComponent(mrnText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(healthPlanNo)
                            .addComponent(healthPlanNoText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(accountNoText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(accountNo))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(licenseNo)
                            .addComponent(licenseNoText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(deviceSerialNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(deviceNo))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(vehicleNo)
                            .addComponent(vehicleSerialNoText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(linkedin)
                            .addComponent(linkedinText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ipAddress)
                            .addComponent(ipAddressText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(uniqueCodeText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(97, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(154, 154, 154)
                    .addComponent(userImage, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(367, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void ssnTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ssnTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ssnTextActionPerformed

    private void mrnTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mrnTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mrnTextActionPerformed

    private void dobTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dobTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dobTextActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Title;
    private javax.swing.JLabel accountNo;
    private javax.swing.JTextField accountNoText;
    private javax.swing.JTextField addressText;
    private javax.swing.JLabel bioLabel;
    private javax.swing.JLabel biometricImage;
    private javax.swing.JLabel deviceNo;
    private javax.swing.JTextField deviceSerialNo;
    private javax.swing.JTextField dobText;
    private javax.swing.JTextField emailText;
    private javax.swing.JLabel faxNo;
    private javax.swing.JTextField faxText;
    private javax.swing.JLabel healthPlanNo;
    private javax.swing.JTextField healthPlanNoText;
    private javax.swing.JLabel ipAddress;
    private javax.swing.JTextField ipAddressText;
    private javax.swing.JLabel licenseNo;
    private javax.swing.JTextField licenseNoText;
    private javax.swing.JLabel linkedin;
    private javax.swing.JTextField linkedinText;
    private javax.swing.JLabel mrn;
    private javax.swing.JTextField mrnText;
    private javax.swing.JTextField nameText;
    private javax.swing.JLabel phoneNo;
    private javax.swing.JTextField phoneNoText;
    private javax.swing.JLabel ssn;
    private javax.swing.JTextField ssnText;
    private javax.swing.JLabel uniqueCodeLabel;
    private javax.swing.JTextField uniqueCodeText;
    private javax.swing.JLabel useEmail;
    private javax.swing.JLabel userAddress;
    private javax.swing.JLabel userDob;
    private javax.swing.JLabel userImage;
    private javax.swing.JLabel userName;
    private javax.swing.JLabel userPhotoLabel;
    private javax.swing.JLabel vehicleNo;
    private javax.swing.JTextField vehicleSerialNoText;
    // End of variables declaration//GEN-END:variables

    private void displayProfile() {
        nameText.setText(userProfile.getUserName());
        addressText.setText(userProfile.getUserAddress());
        dobText.setText(userProfile.getUserDob().toString());
        phoneNoText.setText(Long.toString(userProfile.getPhoneNo()));
        faxText.setText(Long.toString(userProfile.getFax()));
        emailText.setText(userProfile.getUserEmail());
        ssnText.setText(userProfile.getSsn());
        mrnText.setText(userProfile.getMedicalRecord());
        healthPlanNoText.setText(userProfile.getUserHealthPlanNo());
        accountNoText.setText(Long.toString(userProfile.getBankAccountNo()));
        licenseNoText.setText(userProfile.getLicenseNo());
        vehicleSerialNoText.setText(userProfile.getVehicleNo());
        deviceSerialNo.setText(userProfile.getDeviceSerialNo());
        linkedinText.setText(userProfile.getLinkedin());
        ipAddressText.setText(userProfile.getIpAddress());
        icon = new ImageIcon(userProfile.getBiometricIdentifier());
        biometricImage.setIcon(icon);
        icon = new ImageIcon(userProfile.getProfilePhoto());
        userImage.setIcon(icon);
        uniqueCodeText.setText(userProfile.getUniqueIdentifier());
    }
}
