/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI;

import java.text.SimpleDateFormat;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.Date;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;
import model.Car;
import model.CarList;

/**
 *
 * @author choud
 */
public class CreateJPanel extends javax.swing.JPanel {
    private CarList listOfCars;
    private boolean isAvailable;
    private boolean seatsFlag;
    /**
     * Creates new form CreateJPanel
     */
    public CreateJPanel(CarList listOfCars) {
        initComponents();
        this.listOfCars = listOfCars;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblCreateTitle = new javax.swing.JLabel();
        lblManufacture = new javax.swing.JLabel();
        lblSerialNumber = new javax.swing.JLabel();
        lblModel = new javax.swing.JLabel();
        lblManuYear = new javax.swing.JLabel();
        lblSeats = new javax.swing.JLabel();
        lblCity = new javax.swing.JLabel();
        lblCertiYear = new javax.swing.JLabel();
        lblStatus = new javax.swing.JLabel();
        txtManufacture = new javax.swing.JTextField();
        txtSeats = new javax.swing.JTextField();
        txtCity = new javax.swing.JTextField();
        yearManufacture = new com.toedter.calendar.JYearChooser();
        expirationCalendar = new com.toedter.calendar.JCalendar();
        btnAvailable = new javax.swing.JRadioButton();
        btnNA = new javax.swing.JRadioButton();
        txtSerialNo = new javax.swing.JTextField();
        txtModelName = new javax.swing.JTextField();
        btnSave = new javax.swing.JButton();
        lblSeatsError = new javax.swing.JLabel();

        setBackground(new java.awt.Color(0, 153, 153));

        lblCreateTitle.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblCreateTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCreateTitle.setText("Add New Car");

        lblManufacture.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblManufacture.setText("Car Manufacturer:");

        lblSerialNumber.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblSerialNumber.setText("Car Serial Number:");

        lblModel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblModel.setText("Car Model Name:");

        lblManuYear.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblManuYear.setText("Car Manufacture Year: ");

        lblSeats.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblSeats.setText("Total Seats:");

        lblCity.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblCity.setText("Car City:");

        lblCertiYear.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblCertiYear.setText("Maintainence Certificate Expiration Date:");

        lblStatus.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblStatus.setText("Car Status:");

        txtManufacture.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtManufactureActionPerformed(evt);
            }
        });

        txtSeats.setToolTipText("Add digits only between 2-9");
        txtSeats.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtSeatsKeyReleased(evt);
            }
        });

        btnAvailable.setText("Avaliable");
        btnAvailable.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAvailableActionPerformed(evt);
            }
        });

        btnNA.setText("Not Avaliable");
        btnNA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNAActionPerformed(evt);
            }
        });

        btnSave.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnSave.setText("Save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(237, 237, 237)
                        .addComponent(lblCreateTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGap(116, 116, 116)
                                .addComponent(lblManuYear))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(140, 140, 140)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addGroup(layout.createSequentialGroup()
                                            .addGap(5, 5, 5)
                                            .addComponent(lblManufacture)
                                            .addGap(27, 27, 27)
                                            .addComponent(txtManufacture, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createSequentialGroup()
                                            .addGap(43, 43, 43)
                                            .addComponent(lblSeats)
                                            .addGap(27, 27, 27)
                                            .addComponent(txtSeats))
                                        .addGroup(layout.createSequentialGroup()
                                            .addGap(48, 48, 48)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addComponent(lblStatus)
                                                .addComponent(lblCity))
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(layout.createSequentialGroup()
                                                    .addGap(27, 27, 27)
                                                    .addComponent(txtCity))
                                                .addGroup(layout.createSequentialGroup()
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                    .addComponent(btnAvailable, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                        .addComponent(btnNA, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(lblSerialNumber)
                                            .addComponent(lblModel))
                                        .addGap(27, 27, 27)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtSerialNo)
                                            .addComponent(txtModelName)
                                            .addComponent(yearManufacture, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))))
                        .addGap(18, 18, 18)
                        .addComponent(lblSeatsError, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(lblCertiYear)
                        .addGap(18, 18, 18)
                        .addComponent(expirationCalendar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(304, 304, 304)
                        .addComponent(btnSave)))
                .addContainerGap(48, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(lblCreateTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(55, 55, 55)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblManufacture, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtManufacture, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblModel, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtModelName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblSerialNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtSerialNo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblManuYear, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(yearManufacture, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSeats, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtSeats, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblSeatsError, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblCity, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAvailable))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addComponent(lblCertiYear, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(btnNA)
                        .addGap(18, 18, 18)
                        .addComponent(expirationCalendar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(btnSave)
                .addContainerGap(36, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtManufactureActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtManufactureActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtManufactureActionPerformed

    private void btnAvailableActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAvailableActionPerformed
        // TODO add your handling code here:
        if(btnAvailable.isSelected() == true){
            btnNA.setSelected(false);
            isAvailable = true;
        }
    }//GEN-LAST:event_btnAvailableActionPerformed

    private void btnNAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNAActionPerformed
        // TODO add your handling code here:
        if(btnNA.isSelected() == true){
            btnAvailable.setSelected(false);
            isAvailable = false;
        }  
    }//GEN-LAST:event_btnNAActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // TODO add your handling code here:
        SimpleDateFormat format = new SimpleDateFormat("MM/dd/yyyy");
        SimpleDateFormat format1 = new SimpleDateFormat("MM/dd/yyyy HH:mm:ss");
        
        if(txtManufacture.getText().length() > 0 && txtModelName.getText().length() > 0 &&
                txtSerialNo.getText().length() > 0 && yearManufacture.getYear() >= 1550 &&
                txtSeats.getText().length() > 0 && txtCity.getText().length() > 0 &&
                expirationCalendar.getDate() != null && seatsFlag){
        String manufacturer = txtManufacture.getText();
        String model = txtModelName.getText();
        String serialNo = txtSerialNo.getText();
        int manufactureYear = yearManufacture.getYear();
        int seats = Integer.parseInt(txtSeats.getText());
        String city = txtCity.getText();
        boolean status = isAvailable;
        String expirationDate = format.format(expirationCalendar.getDate());
        
        Car car = listOfCars.addNewCar();
        car.setCarManufacturer(manufacturer);
        car.setCarModel(model);
        car.setCarLicenceNo(serialNo);
        car.setCarManufacturerYear(manufactureYear);
        car.setNoOfSeats(seats);
        car.setCarCity(city);
        car.setIsAvailable(status);
        car.setCarMaintainenceCertificate(expirationDate);
        
        Date updatedTime = new Date();
        listOfCars.setUpdatedTime(format1.format(updatedTime));
        JOptionPane.showMessageDialog(this, "Car Added!");
        
        txtManufacture.setText("");
        txtModelName.setText("");
        txtSerialNo.setText("");
        yearManufacture.setValue(2021);
        txtSeats.setText("");
        txtCity.setText("");
        btnAvailable.setSelected(false);
        btnNA.setSelected(false);
        
           // lblUpdatedTime.setText(updatedTime);
       // expirationCalendar.setCalendar(null);
        }
        else {
            JOptionPane.showMessageDialog(this, "Please add correct car details");
        }
    }//GEN-LAST:event_btnSaveActionPerformed

    private void txtSeatsKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSeatsKeyReleased
        // TODO add your handling code here:
        String regex = "^[2-9]{1}$";
        Pattern pattern= Pattern.compile(regex);
        Matcher match=pattern.matcher(txtSeats.getText());
       
        if(txtSeats.getText().length()<=0 || txtSeats.getText().length()>10 || !match.matches()){
        lblSeatsError.setText("Please enter total no of seats, between 2-9");
        seatsFlag = false;
        }
        else {
        lblSeatsError.setText(null);
        seatsFlag = true;
        }
    }//GEN-LAST:event_txtSeatsKeyReleased

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton btnAvailable;
    private javax.swing.JRadioButton btnNA;
    private javax.swing.JButton btnSave;
    private com.toedter.calendar.JCalendar expirationCalendar;
    private javax.swing.JLabel lblCertiYear;
    private javax.swing.JLabel lblCity;
    private javax.swing.JLabel lblCreateTitle;
    private javax.swing.JLabel lblManuYear;
    private javax.swing.JLabel lblManufacture;
    private javax.swing.JLabel lblModel;
    private javax.swing.JLabel lblSeats;
    private javax.swing.JLabel lblSeatsError;
    private javax.swing.JLabel lblSerialNumber;
    private javax.swing.JLabel lblStatus;
    private javax.swing.JTextField txtCity;
    private javax.swing.JTextField txtManufacture;
    private javax.swing.JTextField txtModelName;
    private javax.swing.JTextField txtSeats;
    private javax.swing.JTextField txtSerialNo;
    private com.toedter.calendar.JYearChooser yearManufacture;
    // End of variables declaration//GEN-END:variables
}
